Feature/pplus 1141 / divided interface
spryker-sdk/integrator pull request #42
Opened 2022-08-10 10:44 UTC by VladislavStrelchenko

2022-08-18 23:21 UTC, kalaputsik commented
I suppose the structure below might make our source more readable

```
GlueRelationship
├── AbstractModifier.php
├── Unwire
│   ├── UnwireModifierInterface.php
│   ├── UnwireModifier.php
├── Wire
│   ├── WireModifierInterface.php
│   ├── WireModifier.php
CommonClass
├── CommonClassModifierInterface.php
├── CommonClassModifier.php
ClassConstant
├── ModifierInterface.php
├── Modifier.php
├── Wire
│   ├── WireModifierInterface.php
│   ├── WireModifier.php
├── Unwire
│   ├── UnwireModifierInterface.php
│   ├── UnwireModifier.php
ClassInstance
├── Wire
│   ├── WireModifierInterface.php
│   ├── WireModifier.php
├── Unwire
│   ├── UnwireModifierInterface.php
│   ├── UnwireModifier.php
ClassInstanceModifierStrategy
├── Applicable
│   ├── ApplicableReturnArrayModifierStrategy.php
│   ├── ApplicableReturnChainedCollectionModifierStrategy.php
│   ├── ApplicableReturnClassModifierStrategy.php
│   ├── ApplicableReturnCollectionModifierStrategy.php
│   ├── ApplicableReturnExtendContainerModifierStrategy.php
│   ├── ApplicableInterface.php
├── Unwire
│   ├── UnwireModifierStrategyInterfaceCheck.php
│   ├── UnwireReturnArrayModifierStrategy.php
│   ├── UnwireReturnChainedCollectionModifierStrategy.php
│   ├── UnwireReturnClassModifierStrategy.php
│   ├── UnwireReturnCollectionModifierStrategy.php
│   ├── UnwireReturnExtendContainerModifierStrategy.php
├── Wire
│   ├── WireModifierStrategyInterfaceCheck.php
│   ├── WireReturnArrayModifierStrategy.php
│   ├── WireReturnChainedCollectionModifierStrategy.php
│   ├── WireReturnClassModifierStrategy.php
│   ├── WireReturnCollectionModifierStrategy.php
│   ├── WireReturnExtendContainerModifierStrategy.php
```

2022-08-23 08:10 UTC, kalaputsik commented
@VladislavStrelchenko 
could you check the methods below in the IntegratorFactory and rename them by template **create{ClassName}** 

```
createCopyFileManifestStrategy
createNavigationManifestStrategy
createMethodBodyCreator
createNodeTreeCreator
createClassConstantModifier
createClassBuilderFactory
createWireClassInstanceReturnArrayModifierStrategy
createWireClassInstanceReturnClassModifierStrategy
createUnwireClassInstanceReturnArrayModifierStrategy
createUnwireClassInstanceReturnCollectionModifierStrategy
createUnwireClassInstanceReturnExtendContainerModifierStrategy
createUnwireClassInstanceReturnChainedCollectionModifierStrategy
createUnwireClassInstanceReturnClassModifierStrategy
createCheckApplicableClassInstanceReturnArrayModifierStrategy
createCheckApplicableClassInstanceReturnCollectionModifierStrategy
createCheckApplicableClassInstanceReturnExtendContainerModifierStrategy
createCheckApplicableClassInstanceReturnChainedCollectionModifierStrategy
createCheckApplicableClassInstanceReturnClassModifierStrategy
createArgumentBuider
```

2022-08-23 08:11 UTC, kalaputsik commented on src/IntegratorFactory.php
> +    public function getWireClassInstanceModifierStrategies(): array
what about **getWireModifierStrategies** ?

2022-08-23 08:12 UTC, kalaputsik requested changes

2022-08-23 08:12 UTC, kalaputsik commented on src/IntegratorFactory.php
> +    public function getUnwireClassInstanceModifierStrategies(): array
getUnwireModifierStrategies ?

2022-08-23 08:18 UTC, kalaputsik reviewed
getManifestExecutorStrategies -> getManifestStrategies ?

2022-08-23 09:36 UTC, kalaputsik commented on src/Builder/ClassModifier/ClassConstant/Unwire/UnwireModifierInterface.php
> +    public function unwireClassConstant(
unwire ?

2022-08-23 09:51 UTC, kalaputsik commented
**ClassConstant**
src/Builder/ClassModifier/ClassConstant/Unwire/UnwireModifier.php
src/Builder/ClassModifier/ClassConstant/Unwire/UnwireModifierInterface.php
execution in ClassBuilderFacade
**unwireClassConstant -> unwire**

src/Builder/ClassModifier/ClassConstant/Wire/WireModifier.php
src/Builder/ClassModifier/ClassConstant/Wire/WireModifierInterface.php
execution in ClassBuilderFacade
**wireClassConstant -> wire**

---

**ClassInstance**
src/Builder/ClassModifier/ClassInstance/Unwire/UnwireModifier.php
src/Builder/ClassModifier/ClassInstance/Unwire/UnwireModifierInterface.php
execution in ClassBuilderFacade
**unwireClassInstance -> unwire**

src/Builder/ClassModifier/ClassInstance/Wire/WireModifier.php
src/Builder/ClassModifier/ClassInstance/Wire/WireModifierInterface.php
execution in ClassBuilderFacade
**wireClassInstance -> wire**

---

**GlueRelationship**
src/Builder/ClassModifier/GlueRelationship/Unwire/UnwireModifier.php
src/Builder/ClassModifier/GlueRelationship/Unwire/UnwireModifierInterface.php
execution in ClassBuilderFacade
**unwireGlueRelationship -> unwire**

src/Builder/ClassModifier/GlueRelationship/Wire/WireModifier.php
src/Builder/ClassModifier/GlueRelationship/Wire/WireModifierInterface.php
execution in ClassBuilderFacade
**wireGlueRelationship -> wire**

2022-08-23 11:35 UTC, VladislavStrelchenko commented on src/IntegratorFactory.php
> +    public function getWireClassInstanceModifierStrategies(): array
Thanks ++

2022-08-23 11:35 UTC, VladislavStrelchenko commented on src/IntegratorFactory.php
> +    public function getUnwireClassInstanceModifierStrategies(): array
++

2022-08-23 18:48 UTC, kalaputsik approved these changes

2022-08-26 11:55 UTC, merged